SELECT EFTERNAMM,FORENAMM FROM AUTHORS WHERE ID = (
  SELECT ID
  FROM BOOKS
  WHERE TITLE = 'The Shining'
);

SELECT TITLE FROM BOOKS WHERE ID = (
  SELECT ID
  FROM AUTHORS
  WHERE FORENAMM = 'Paulette' AND EFTERNAMM = 'Bourgeois'
);

SELECT EFTERNAMM , FORENAMM FROM CUSTOMERS WHERE ID IN (
	SELECT C_ID FROM SHIPMENTS WHERE ISBN IN (
		SELECT ISBN FROM EDITIONS WHERE ID IN (
			SELECT ID FROM BOOKS WHERE SUB_ID IN (
				SELECT SUB_ID FROM SUBJECTS WHERE SUBJECT = 'Horror'
			)
		)
	)
);

SELECT TITLE FROM BOOKS WHERE ID = (
	SELECT ID FROM EDITIONS WHERE ISBN = (
		SELECT ISBN FROM STOCK WHERE STOCK = (
			SELECT MAX(STOCK) FROM STOCK
		)
	)
);

SELECT TITLE FROM BOOKS
	INNER JOIN EDITIONS ON BOOKS.ID =EDITIONS.ID
	INNER JOIN STOCK ON EDITIONS.ISBN= STOCK.ISBN
WHERE STOCK = (
	SELECT MAX(STOCK) FROM STOCK
);

SELECT SUM(F_PRICE) FROM STOCK
	INNER JOIN EDITIONS ON STOCK.ISBN=EDITIONS.ISBN
	INNER JOIN BOOS ON EDITIONS.ID=BOOKS.ID
	INNER JOIN SUBJECT ON BOOKS.S_ID = SUBJECTS.S_ID
WHERE SUBJECT = 'Science Fiction';

SELECT TITLE FROM BOOKS
	INNER JOIN EDITIONS ON BOOKS.ID =EDITIONS.ID
	INNER JOIN SHIPMENTS ON EDITIONS.ISBN=SHIPMENTS.ISBN
GROUP BY BOOKS.TITLE HAVING COUNT(CUSTOMERS(ID)) = 2;

SELECT SUM(F_PRICE - COST) FROM SHIPMENTS,STOCK WHERE SHIPMENTS.ISBN=STOCK.ISBN

SELECT EFTERNAMM,FORENAMM FROM CUSTOMERS
	INNER JOIN SHIPMENTS ON CUSTOMERS.ID=SHIPMENTS.C_ID
	INNER JOIN EDITIONS ON SHIPMENTS.ISBN = EDITIONS.ISBN
	INNER JOIN BOOKS ON EDITIONS.ID = BOOKS.ID
	INNER JOIN SUBJECTS ON BOOKS.SUB_ID=EDITIONS.SUB_ID
GROUP BY CUSTOMERS.EFTERNAMM, CUSTOMERS.FORENAMM
HAVING COUNT(SUBJECTS.S_ID) > 2;

SELECT SUBJECT FROM SUBJECTS WHERE SUBJECT NOT IN (
	SELECT DISTINCT SUBJECT
	FROM SHIPMENTS,EDITIONS,BOOKS,SUBJECTS
  	WHERE (SHIPMENTS.ISBN=BOOKS.ISBN AND EDITIONS.ID=BOOK.ID AND BOOKS.SUB_ID=SUBJECTS.ID)
);
