CREATE VIEW ISBN_TITLE AS
  SELECT ISBN, TITLE FROM EDITIONS,BOOKS WHERE EDITIONS.ID=BOOKS.ID
DROP VIEW ISBN_TITLE;

--WONT EXECUTE, VIOLATES CONSTRAINT. SINCE THIS BOOK.ID DOESNT EXIST WE MUST EITHER INSERT IT 1ST OR IT SHOULD ARLREADY EXIST THERE
INSERT INTO EDITIONS(ISBN, ID, EDITION, P_ID DT) VALUES ('5555', 12345, 1, 59, '2012-12-02');

--WONT EXECUTE, VIOLATES INTEGRITY. FIEDS MUST NOT BE NULL
INSERT INTO EDITIONS(ISBN) VALUES ('5555');

INSERT INTO BOOKS(ID,TITLE) VALUES (12345, 'How I Insert');

INSERT INTO EDITIONS(ISBN, ID, EDITION, P_ID DT) VALUES ('5555', 12345, 1, 59, '2012-12-02');

SELECT * FROM BOOKS;

UPDATE BOOKS SET SUB_ID = 10 WHERE ID = 12345;

--WONT EXECUTE, VIOLATES FOREIGN KEY CONSTRAINT, IT HAS TO BE DELETED FIRST FROM THE OTHER TABLE(CORRECT ORDER)
DELETE FROM BOOKS WHERE ID = 12345;

DELETE FROM EDITIONS WHERE ID = 12345;

DELETE FROM BOOKS WHERE ID = 12345;

--WONT EXECUTE, VIOLATES FOREIGN KEY CONSTRAINT, UPDATE IN THE DEPENDENT TABLE THEN EXECUTE THE QUERY
INSERT INTO BOOKS(ID,TITLE.SUB_ID) VALUES(12345,'How I Insert',3443);

ALTER TABLE BOOKS ADD CONSTRAINT HAS_SUB CHECK (SUB_ID IS NOT NULL);

INSERT INTO SUBJECTS(ID) VALUES(99);

INSERT INTO BOOKS(ID,TITLE,SUB_ID) VALUES (12321,'test',99);

DELETE FROM BOOKS WHERE SUB_ID = 99;

DELETE FROM SUBJECTS WHERE SUB_ID = 99;

INSERT INTO BOOKS(ID,TITLE) VALUES (12321,'test');
