CREATE FUNCTION DSTOCK() RETURNS TRIGGER AS $PNAME$
	BEGIN
		IF (SELECT STOCK FROM STOCK WHERE STOCK.ISBN=NEW.ISBN) = 0
			THEN RAISE EXCEPTION 'There is no stock to ship';
		ELSE
			UPDATE STOCK
			SET STOCK =STOCK - 1
			WHERE STOCK.ISBN=NEW.ISBN;
		END IF;
		RETURN NEW;
	END;

$PNAME$ LANGUAGE PLPGSQL;

CREATE TRIGGER STOCKTRIGGER BEFORE INSERT ON SHIPMENTS FOR EACH ROW EXECUTE PROCEDURE DSTOCK();

INSERT INTO SHIPMENTS VALUES (2000, 860, '0394900014', '2012-12-07');

INSERT INTO SHIPMENTS VALUES (2001, 860, '044100590X', '2012-12-07');

DELETE FROM SHIPMENTS WHERE ID > 1999;

UPDATE STOCK SET STOCK = 89 WHERE ISBN = '044100590X';

DROP FUNCTION DSTOCK() CASCADE;
